# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main




stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
  pool: 
    name: LOCAL_MACHINE  

    steps:
    - template: templates/sonar-prepare.yml
    - task: ExtractFiles@1
      inputs:
      archiveFilePatterns: '*.zip'
      destinationFolder: '$(Build.SourcesDirectory)'
      cleanDestinationFolder: false
    - task: Maven@3
      inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify sonar:sonar'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: JaCoCo
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop
    - template: templates/sonar-execute.yml