# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main




stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
  pool: 
    name: Pipeline Self Hosted  

    steps:
    - task: SonarCloudPrepare@1
      displayName: Prepare analysis on SonarCloud
      inputs:
       SonarCloud: Sonar-Java
       organization: fmossamih01
       projectKey: fmossamih_JavaWebApplication
       projectName: JavaWebApplication
    - task: Maven@3
      displayName: Maven Package
      inputs:
       mavenPomFile: 'pom.xml'
    - task: CopyFiles@2
      displayName: Copy Files to artifact staging directory
      inputs:
       SourceFolder: '$(System.DefaultWorkingDirectory)'
       Contents: '**/target/*.?(war|jar)'
       TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop
    - task: SonarCloudAnalyze@1
      displayName: Run Code Analysis
    - task: SonarCloudPublish@1
      displayName: Publish Quality Gate Result